### ISSUE TITLE
LinkedIn URL is broken

### ISSUE THREAD

**Issue by fehmisener** [MelihSelamiUrkmezz/MelihSelamiUrkmezz#1]
https://github.com/MelihSelamiUrkmezz/MelihSelamiUrkmezz/blob/cc287b0b305fc2a350b7700c82001c027cc9bdcb/README.md?plain=1#L4

**Comment by MelihSelamiUrkmezz** [comment]
Thank you Fehmi! I changed this url.

**Comment by MelihSelamiUrkmezz** [comment]
Thank you Fehmi! I changed this!
